"""Domain models for the course builder.

This module contains all the core data models used throughout the application:
- books: Book-related models (Book, LibgenResult, DownloadedBook, etc.)
- course: Course structure models (CourseSkeleton, CourseModule, etc.)
- content: Content generation models (CapsuleItem, SourceReference, etc.)
- validation: Validation and correction models
"""

from course_builder.domain.books import (
    Book,
    DownloadedBook,
    ExtractedChunk,
    LibgenResult,
    ProcessedBook,
    Step1Output,
    Step2Output,
    Step3Output,
)
from course_builder.domain.content import (
    AnswerChoice,
    BlankSlot,
    CapsuleItem,
    CapsuleItemGenerationResult,
    CaseStudyQuestion,
    Course,
    DragDropItem,
    DragDropQuestion,
    DropZone,
    FillBlankQuestion,
    HotspotQuestion,
    HotspotRegion,
    ItemSourceReference,
    MultipleChoiceQuestion,
    MultipleResponseQuestion,
    OrderingQuestion,
    PracticeQuestion,
    PracticeQuestionBase,
    SimulationQuestion,
    SimulationTask,
    SourceChunkSnapshot,
    SourceCitation,
    SourceHighlight,
    SourceReference,
    Step5Output,
    TopicContent,
    TopicContentResult,
)
from course_builder.domain.course import (
    Capsule,
    CapsuleGenerationResult,
    CourseModule,
    CourseOverview,
    CourseSkeleton,
    CourseTopic,
    DomainModuleResult,
    ExamComponent,
    ExamDomain,
    ExamDomainV2,
    ExamFormat,
    ExamFormatV2,
    ExplanationTemplate,
    ItemClass,
    Lab,
    LabGenerationResult,
    LearningObjective,
    QuestionType,
    QuestionTypeGuide,
    ReasoningTemplate,
    SourceFact,
    Step4Output,
    StudyStrategy,
    SubTopic,
)
from course_builder.domain.schema import (
    CertificationSchema,
    ExhibitField,
    ExhibitType,
    QuestionTypeSchema,
    ScenarioTemplate,
    SchemaLearningOutput,
)
from course_builder.domain.validation import (
    CorrectionAction,
    CorrectionQueue,
    Step6Output,
    ValidationIssue,
    ValidationReport,
    ValidationResult,
)

__all__ = [
    # Books
    "Book",
    "LibgenResult",
    "DownloadedBook",
    "ProcessedBook",
    "ExtractedChunk",
    "Step1Output",
    "Step2Output",
    "Step3Output",
    # Course (V1 - Legacy)
    "ExamDomain",
    "QuestionType",
    "ExamFormat",
    "Step4Output",
    # Course (V2 - Improved)
    "SourceFact",
    "ItemClass",
    "ExamDomainV2",
    "ExamComponent",
    "ExamFormatV2",
    "ReasoningTemplate",
    "ExplanationTemplate",
    "QuestionTypeGuide",
    "Capsule",
    "Lab",
    "SubTopic",
    "LearningObjective",
    "CourseTopic",
    "CourseModule",
    "StudyStrategy",
    "CourseOverview",
    "DomainModuleResult",
    "LabGenerationResult",
    "CapsuleGenerationResult",
    "CourseSkeleton",
    # Content
    "SourceCitation",
    "SourceChunkSnapshot",
    "ItemSourceReference",
    "CapsuleItem",
    "CapsuleItemGenerationResult",
    "SourceHighlight",
    "SourceReference",
    "AnswerChoice",
    "PracticeQuestionBase",
    "MultipleChoiceQuestion",
    "MultipleResponseQuestion",
    "DragDropItem",
    "DropZone",
    "DragDropQuestion",
    "HotspotRegion",
    "HotspotQuestion",
    "BlankSlot",
    "FillBlankQuestion",
    "OrderingQuestion",
    "SimulationTask",
    "SimulationQuestion",
    "CaseStudyQuestion",
    "PracticeQuestion",
    "TopicContent",
    "TopicContentResult",
    "Course",
    "Step5Output",
    # Schema
    "ExhibitField",
    "ExhibitType",
    "ScenarioTemplate",
    "QuestionTypeSchema",
    "CertificationSchema",
    "SchemaLearningOutput",
    # Validation
    "ValidationIssue",
    "ValidationResult",
    "ValidationReport",
    "CorrectionAction",
    "CorrectionQueue",
    "Step6Output",
]
